# -*- coding: utf-8 -*-
"""
/***************************************************************************
 survey_calculator
                                 A QGIS plugin
 Polar Join Computation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-09
        copyright            : (C) 2022 by Jcad
        email                : jcad.contact@jcad
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load survey_calculator class from file survey_calculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .survey_calculator import survey_calculator
    return survey_calculator(iface)
